site:
  title: Modelix Documentation
  url: https://docs.modelix.org
  start_page: modelix::index.adoc

content:
  sources:

  - url: https://github.com/modelix/modelix.doc
  # - url: ./
    branches:
    tags: 2@({0..9}).R+({0..9})
    start_path: docs


  - url: https://github.com/modelix/modelix-samples
  # - url: ./../modelix-sample-feature
    branches:
    tags: 2@({0..9}).R+({0..9})
    start_path: docs/global


  - url: https://github.com/modelix/modelix-samples
  # - url: ./../modelix-sample-feature
    branches:
    # tags: +({0..9}).+({0..9}).*
    tags:
      (?<version>+({0..9}).+({0..9})).*: $<version>
    start_path: docs/local


urls:
  latest_version_segment: latest
  latest_version_segment_strategy: redirect:to

ui:
  bundle:
    url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/HEAD/raw/build/ui-bundle.zip?job=bundle-stable
    snapshot: true
  supplemental_files: ./docs/ui

antora:
  extensions:
  - require: '@antora/lunr-extension'

asciidoc:
  attributes:
    page-pagination: true
    page-partial: true


