site:
  title: Modelix Documentation
  url: https://docs.modelix.org
  start_page: modelix::index.adoc

content:
  branches: [ HEAD, 'docs/release/*' ]
  sources:

  #
  # GLOBAL REPOSITORIES
  #
  # - url: https://github.com/modelix/modelix.doc
  - url: ./
    version:
      'docs/release/(*)': '$1'
    start_path: docs

  # - url: https://github.com/modelix/modelix.samples
  - url: ./../modelix.samples-main
    version:
      'docs/release/(*)': '$1'
    start_path: docs/global

  # - url: https://github.com/modelix/modelix.core
  - url: ./../modelix.core-main
    version:
      'docs/release/(*)': '$1'
    start_path: docs/global

  # - url: https://github.com/modelix/modelix.platform
  - url: ./../modelix.platform
    version:
      'docs/release/(*)': '$1'
    start_path: docs/global


  #
  # LOCAL  REPOSITORIES
  #
  # - url: https://github.com/modelix/modelix.samples
#  - url: ./../modelix.samples-main
#    version:
#      'docs/release/(*)': '$1'
#    start_path: docs/local
#
#  # - url: https://github.com/modelix/modelix.core
#  - url: ./../modelix.core-main
#    version:
#      'docs/release/(*)': '$1'
#    start_path: docs/local
#
#  # - url: https://github.com/modelix/modelix.platform
#  - url: ./../modelix.platform
#    version:
#      'docs/release/(*)': '$1'
#    start_path: docs/local


urls:
  latest_prerelease_version_segment: main

ui:
  bundle:
    url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/HEAD/raw/build/ui-bundle.zip?job=bundle-stable
    snapshot: true
  supplemental_files: ./docs/ui

antora:
  extensions:
  - require: '@antora/lunr-extension'

asciidoc:
  sourcemap: true
  attributes:
    page-pagination: true
    page-partial: true

runtime:
  log:
    failure_level: error
