site:
  title: Modelix Documentation
  url: https://docs.modelix.org
  start_page: modelix::index.adoc

content:
  sources:

  #
  # GLOBAL REPOSITORIES
  #
  - url: https://github.com/modelix/modelix.doc
  # - url: ./
    branches:
    tags: v2@({0..9}).+({0..9})
    start_path: docs

  - url: https://github.com/modelix/modelix-samples
  # - url: ./../modelix-sample-feature
    branches:
    tags: v2@({0..9}).+({0..9})
    start_path: docs/global

  - url: https://github.com/modelix/modelix.core
  # - url: ./../modelix.core-main
    branches: feature/improved-documentation
    tags: v2@({0..9}).+({0..9})
    start_path: docs/global


  #
  # LOCAL  REPOSITORIES
  #
  - url: https://github.com/modelix/modelix-samples
  # - url: ./../modelix-sample-feature
    branches: feature/improved-documentation
    tags: '*.*'
    # tags: +({0..9}).+({0..9}).*
    # tags:
    #   (+({0..9}).+({0..9})).+({0..9}): $1
    start_path: docs/local

  - url: https://github.com/modelix/modelix.core
  # - url: ./../modelix.core-main
    branches: feature/documentation-setup
    tags: ['v*.*']
    start_path: docs/local


urls:
  latest_version_segment: latest
  latest_version_segment_strategy: redirect:to

ui:
  bundle:
    url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/HEAD/raw/build/ui-bundle.zip?job=bundle-stable
    snapshot: true
  supplemental_files: ./docs/ui

antora:
  extensions:
  - require: '@antora/lunr-extension'

asciidoc:
  attributes:
    page-pagination: true
    page-partial: true

