site:
  title: Modelix Documentation
  url: https://docs.modelix.org
  start_page: modelix::index.adoc

content:
  sources:

  #
  # GLOBAL REPOSITORIES
  # These are tied to the single 'Modelix Documentation'
  #
  - url: https://github.com/modelix/modelix.doc
    branches: HEAD
    tags: modelix-2@({0..9}).+({0..9})
    start_path: docs

  - url: https://github.com/modelix/modelix.samples
    branches: HEAD
    tags: modelix-2@({0..9}).+({0..9})
    start_path: docs/global

  - url: https://github.com/modelix/modelix.core
    branches: HEAD
    tags: modelix-2@({0..9}).+({0..9})
    start_path: docs/global

  - url: https://github.com/modelix/modelix.platform
    branches: HEAD
    tags: modelix-2@({0..9}).+({0..9})
    start_path: docs/global


  #
  # LOCAL  REPOSITORIES
  # Provides individual per repository documentation
  #
  - url: https://github.com/modelix/modelix.samples
    branches: HEAD
    tags: modelix-2@({0..9}).+({0..9})
    start_path: docs/local

  - url: https://github.com/modelix/modelix.core
    branches: HEAD
    tags: modelix-2@({0..9}).+({0..9})
    start_path: docs/local

  - url: https://github.com/modelix/modelix.platform
    branches: HEAD
    tags: modelix-2@({0..9}).+({0..9})
    start_path: docs/local


urls:
  latest_version_segment: latest
  latest_version_segment_strategy: redirect:to

ui:
  bundle:
    url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/HEAD/raw/build/ui-bundle.zip?job=bundle-stable
    snapshot: true
  supplemental_files: ./docs/ui

antora:
  extensions:
  - require: '@antora/lunr-extension'

asciidoc:
  attributes:
    page-pagination: true
    page-partial: true


