name: Publish to GitHub Pages
on:
  workflow_dispatch:
  push:
    tags:
      - 'modelix-2[0-9]+.[0-9]+'
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Install Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'
    - name: Install Antora dependencies
      run: npm ci
    - name: Generate Site
      run: npx antora --stacktrace antora-playbook.yml
    - name: Publish to GitHub Pages
      if: github.event_name == 'push' && contains(github.ref, 'refs/tags/')
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: build/site

